In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("mode.chained_assignment", None)

In [81]:
flt_rep = pd.read_clipboard()

In [46]:
bssc_flt = pd.read_clipboard()

In [47]:
bssc = pd.read_clipboard()

In [48]:
ag = pd.read_clipboard()

In [49]:
flt_oe = pd.read_clipboard()

In [76]:
bssc_flt.columns = ['P code', '規格', '花紋', '產地', '通路', '5月', '6月', '7月', '8月', '9月',
       '10月', '11月', '12月']
ag.columns = ['P code', '規格', '花紋', '產地', '通路', '5月', '6月', '7月', '8月', '9月',
       '10月', '11月', '12月']
bssc.columns = ['P code', '規格', '花紋', '產地', '通路', '5月', '6月', '7月', '8月', '9月',
       '10月', '11月', '12月']
flt_oe.columns = ['P code', '規格', '花紋', '產地', '通路', '5月', '6月', '7月', '8月', '9月',
       '10月', '11月', '12月']
flt_rep.columns = ['P code', '規格', '花紋', '產地', '通路', '5月', '6月', '7月', '8月', '9月',
       '10月', '11月', '12月']

In [51]:
result = pd.concat([bssc, bssc_flt, ag, flt_oe, flt_rep])

In [82]:
result = flt_rep

In [83]:
result = result.fillna(0)

In [84]:
result

,P code,規格,花紋,產地,通路,5月,6月,7月,8月,9月,10月,11月,12月
0,TBR0L154,1000R20,R156,TBSC,FLT-REP,0,0,0,0,0,0,0,0
1,TBR0L098,1100R20,M840,TBSC,FLT-REP,0,0,0,0,0,0,0,0
2,TBR0L112,1100R20,R156,BTMT,FLT-REP,0,0,0,0,0,0,0,0
3,TBR02513,1400R20,R180,BSJ,FLT-REP,0,0,0,0,0,0,0,0
4,TBR08329,1400R20,VSJ,BSJ,FLT-REP,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,LSR03459,9.5R17.5,R294,BSJ,FLT-OE,0,0,0,0,0,0,0,0
316,LSR05127,205/75R17.5,R294,BSJ,FLT-OE,0,0,0,0,0,0,0,0
317,LSR08435,215/75R17.5,R294,BSJ,FLT-OE,0,0,0,0,0,0,0,0
318,LSR03763,225/75R17.5,R294,BSJ,FLT-OE,0,0,0,0,0,0,0,0
319,LSR03765,235/75R17.5,R294,BSJ,FLT-OE,0,0,0,0,0,0,0,0

In [85]:
result = result.astype({"5月": int, "6月": int, "7月": int, "8月": int, "9月": int, "10月": int, "11月": int, "12月": int})

In [86]:
rolling_forecast = result.groupby(['P code', '規格', '花紋', '產地', '通路']).sum().stack().reset_index(name="數量")

In [87]:
rolling_forecast

        P code       規格    花紋    產地       通路 level_5  數量
0     LSR01180   750R16  R225   BSJ       AG      5月  19
1     LSR01180   750R16  R225   BSJ       AG      6月  22
2     LSR01180   750R16  R225   BSJ       AG      7月  27
3     LSR01180   750R16  R225   BSJ       AG      8月  27
4     LSR01180   750R16  R225   BSJ       AG      9月  23
...        ...      ...   ...   ...      ...     ...  ..
2555  TBR0L154  1000R20  R156  TBSC  FLT-REP      8月   0
2556  TBR0L154  1000R20  R156  TBSC  FLT-REP      9月   0
2557  TBR0L154  1000R20  R156  TBSC  FLT-REP     10月   0
2558  TBR0L154  1000R20  R156  TBSC  FLT-REP     11月   0
2559  TBR0L154  1000R20  R156  TBSC  FLT-REP     12月   0

[2560 rows x 7 columns]

In [88]:
rolling_forecast["數量"].sum()

88948

In [89]:
rolling_forecast = rolling_forecast.rename(columns={"level_5": "月份"})

In [93]:
rolling_forecast[rolling_forecast["數量"] > 0]

        P code       規格    花紋    產地    通路   月份  數量
0     LSR01180   750R16  R225   BSJ    AG   5月  19
1     LSR01180   750R16  R225   BSJ    AG   6月  22
2     LSR01180   750R16  R225   BSJ    AG   7月  27
3     LSR01180   750R16  R225   BSJ    AG   8月  27
4     LSR01180   750R16  R225   BSJ    AG   9月  23
...        ...      ...   ...   ...   ...  ...  ..
2531  TBR0L154  1000R20  R156  TBSC  BSSC   8月   6
2532  TBR0L154  1000R20  R156  TBSC  BSSC   9月   6
2533  TBR0L154  1000R20  R156  TBSC  BSSC  10月   6
2534  TBR0L154  1000R20  R156  TBSC  BSSC  11月   6
2535  TBR0L154  1000R20  R156  TBSC  BSSC  12月   6

[962 rows x 7 columns]

In [94]:
rolling_forecast.to_excel(r"C:\Users\kc.hsu\Desktop\20220531_RT3.xlsx", index=False)

### BSSC-FLT價格整理

In [7]:
sc_flt_price = pd.read_clipboard()

In [21]:
sc_new_price = sc_flt_price[["物料", "物料.1", "交易價(未稅)"]].drop_duplicates()

In [44]:
sc_new_price = sc_new_price.groupby(["物料", "物料.1"]).apply(lambda x: x["交易價(未稅)"].min()).reset_index(name="未稅最低價")

In [111]:
rt3 = pd.read_clipboard()

In [108]:
sc_flt_dict = dict(zip(sc_new_price["物料"], sc_new_price["未稅最低價"]))

In [117]:
rt3["Current NET"] = rt3.apply(lambda x: sc_flt_dict[x["P code"]] if x["通路"] == "BSSC-FLT" else x["Current NET"], axis=1)

In [118]:
rt3.to_excel(r"C:\Users\kc.hsu\Desktop\20220531_RT3_v2.xlsx", index=False)

## FLT-OE價格整理

In [142]:
oe = pd.read_clipboard()

In [143]:
oe[['SCANIA', 'VOLVO',
       'DAF', '成運', '金龍', '乾佑', '群翔', '華德', '凱勝', '創奕']] = oe[['SCANIA', 'VOLVO',
       'DAF', '成運', '金龍', '乾佑', '群翔', '華德', '凱勝', '創奕']].fillna(999999999)

In [144]:
oe[['SCANIA', 'VOLVO', 'DAF', '成運', '金龍', '乾佑', '群翔', '華德', '凱勝', '創奕']].astype(int)

,SCANIA,VOLVO,DAF,成運,金龍,乾佑,群翔,華德,凱勝,創奕
0,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
1,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
2,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
3,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
4,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
5,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
6,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
7,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
8,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
9,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
10,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
11,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
12,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
13,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
14,999999999,999999999,999999999,999999999,4830,999999999,999999999,999999999,999999999,999999999
15,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
16,999999999,999999999,999999999,999999999,4560,999999999,999999999,999999999,999999999,999999999
17,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
18,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
19,999999999,999999999,999999999,999999999,6400,5044,5296,999999999,999999999,999999999
20,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
21,999999999,999999999,5800,999999999,6650,999999999,999999999,999999999,999999999,999999999
22,999999999,999999999,999999999,999999999,8408,999999999,999999999,9300,999999999,999999999
23,999999999,999999999,999999999,999999999,999999999,999999999,999999999,7700,999999999,999999999
24,999999999,999999999,999999999,7100,6900,999999999,999999999,999999999,999999999,999999999
25,999999999,999999999,999999999,8660,8000,9700,9860,8600,999999999,8600
26,999999999,999999999,999999999,999999999,999999999,999999999,8500,999999999,999999999,999999999
27,9488,999999999,999999999,999999999,999999999,999999999,10490,999999999,999999999,999999999
28,9488,999999999,999999999,999999999,999999999,999999999,10490,999999999,999999999,999999999
29,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
30,9710,999999999,999999999,999999999,999999999,10100,10805,999999999,999999999,999999999
31,9488,999999999,999999999,999999999,999999999,8700,9450,999999999,999999999,999999999
32,999999999,999999999,999999999,7300,8000,999999999,999999999,999999999,999999999,999999999
33,999999999,999999999,999999999,999999999,8000,999999999,999999999,999999999,999999999,999999999
34,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
35,999999999,999999999,999999999,999999999,9100,999999999,999999999,999999999,999999999,999999999
36,9203,8900,999999999,8100,9100,9800,999999999,999999999,999999999,999999999
37,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
38,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
39,999999999,9000,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
40,999999999,999999999,999999999,999999999,999999999,10500,11160,999999999,999999999,999999999
41,999999999,999999999,999999999,999999999,999999999,999999999,8500,999999999,999999999,999999999
42,9317,9150,9000,999999999,999999999,10484,11208,999999999,999999999,999999999
43,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
44,9503,9350,9200,999999999,999999999,11004,999999999,999999999,999999999,999999999
45,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
46,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
47,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
48,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
49,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
50,999999999,999999999,999999999,999999999,999999999,10053,999999999,999999999,999999999,999999999
51,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
52,10608,10700,999999999,999999999,16125,13200,13820,999999999,999999999,999999999
53,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999
54,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999,999999999

In [146]:
oe["最低未稅價格"] = oe[['SCANIA', 'VOLVO', 'DAF', '成運', '金龍', '乾佑', '群翔', '華德', '凱勝', '創奕']].min(axis=1)

In [153]:
result = oe[oe["最低未稅價格"] != 999999999]

In [162]:
result[["P CODE", "規格"]].to_dict()

{'P CODE': {14: 'LVR0F077',
  16: 'LSR03743',
  19: 'LSR03765',
  21: 'TBR09920',
  22: 'TBR05258',
  23: nan,
  24: 'TBR0H460',
  25: 'TBR0J458',
  26: 'TBR0H349',
  27: 'TBR04720',
  28: 'TBR0J067',
  30: 'TBR0J228',
  31: 'TBR0J085',
  32: 'TBR0H351',
  33: nan,
  35: 'TBR0J247',
  36: 'TBR0J295',
  39: 'TBR0J394',
  40: 'TBR0J136',
  41: 'TBR0H350',
  42: 'TBR0J600',
  44: 'TBR0J487',
  50: 'TBR0J314',
  52: 'TBR0J414'},
 '規格': {14: '205/75R17.5',
  16: '215/75R17.5',
  19: '235/75R17.5',
  21: '245/70R17.5',
  22: '255/70R22.5',
  23: '275/70R22.5',
  24: '275/70R22.5',
  25: '275/70R22.5',
  26: '12R22.5',
  27: '12R22.5',
  28: '12R22.5',
  30: '12R22.5',
  31: '12R22.5',
  32: '295/80R22.5',
  33: '295/80R22.5',
  35: '295/80R22.5',
  36: '295/80R22.5',
  39: '295/80R22.5',
  40: '315/80R22.5',
  41: '315/80R22.5',
  42: '315/80R22.5',
  44: '315/80R22.5',
  50: '315/80R22.5',
  52: '385/65R22.5'}}