In [2]:
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("mode.chained_assignment", None)

## RT2 vs ACT in May comparison

In [304]:
df = pd.read_clipboard()

In [305]:
df["年月"] = df["年月"].astype(str)

In [306]:
act = df[(df["年月"] == "202205")]

In [307]:
comparison = act.copy()

In [308]:
comparison.reset_index(drop=True, inplace=True)

In [309]:
act.reset_index(drop=True, inplace=True)

In [310]:
comparison[(comparison["GROUP別"] == "TBR") & (comparison["通路-客戶"] == "FLT-REP") & (comparison["SECTION"] == "315/80") & (comparison["花紋"] == "R294")]

,年月,種類,通路明細,通路-客戶,營業所,舊分類,國別,商品代號,規格,條數,Gross,discount,NET金額,大通路分類,單位膠重,總膠重,MTP,預算/前實績,INCH,成本,營業費,花紋,花紋系列,SECTION,GROUP別,KA分類,國內市場財別,其他業外調整
9,202205,外胎,FT,FLT-REP,本社,TBR,進口,TBR0J136,315/80R225 B54M R294Z,73,1082809.0,123589.0,959220.0,REP,29.71,2168.83,TR3,RT2,TBR→225,757783.8,98787.46519,R294,RIB,315/80,TBR,TBR(G),TBR(G),NaN

In [311]:
comparison[(comparison["GROUP別"] == "TBR") & (comparison["通路-客戶"] == "販社") & (comparison["花紋"].str.contains("FS|D")) & (comparison["預算/前實績"] == "22ACT")]

,年月,種類,通路明細,通路-客戶,營業所,舊分類,國別,商品代號,規格,條數,Gross,discount,NET金額,大通路分類,單位膠重,總膠重,MTP,預算/前實績,INCH,成本,營業費,花紋,花紋系列,SECTION,GROUP別,KA分類,國內市場財別,其他業外調整
182,202205,外胎,A,販社,台中,TBR,進口,TBR0J53F,315/80R22.5 154M D600BZ,20,230100.0,49471.0,180629.0,REP,35.726,714.520,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,315/80,TBR,TBR(G),TBR(G),NaN
252,202205,外胎,FMC,販社,台中,TBR,進口,TBR0JA4F,315/80R225 B54M F400EZ,20,257140.0,56237.0,200903.0,REP,30.649,612.980,TR3,22ACT,TBR→225,NaN,NaN,FS400,Firestone,315/80,TBR,TBR(G),TBR(G),NaN
295,202205,外胎,BSSC-FLT,販社,台南,TBR,進口,TBR0JA4F,315/80R225 B54M F400EZ,15,192855.0,69285.0,123570.0,REP,30.649,459.735,TR3,22ACT,TBR→225,NaN,NaN,FS400,Firestone,315/80,TBR,TBR(G),TBR(G),NaN
409,202205,外胎,DS,販社,員林,TBR,進口,TBR0J53F,315/80R22.5 154M D600BZ,0,0.0,286.0,-286.0,REP,35.726,0.000,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,315/80,TBR,TBR(G),TBR(G),NaN
453,202205,外胎,A,販社,高雄,TBR,進口,TBR0J53F,315/80R22.5 154M D600BZ,2,23010.0,4948.0,18062.0,REP,35.726,71.452,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,315/80,TBR,TBR(G),TBR(G),NaN
460,202205,外胎,BSSC-FLT,販社,高雄,TBR,進口,TBR0J37F,12R22.5 16 152L F400CZ,60,667980.0,252390.0,415590.0,REP,28.380,1702.800,TR3,22ACT,TBR→225,NaN,NaN,FS400,Firestone,12,TBR,TBR(G),TBR(G),NaN
465,202205,外胎,BSSC-FLT,販社,高雄,TBR,進口,TBR0J77F,12R22.5 16 152L D600Z,6,70230.0,28170.0,42060.0,REP,32.194,193.164,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,12,TBR,TBR(G),TBR(G),NaN
466,202205,外胎,BSSC-FLT,販社,高雄,TBR,進口,TBR0JA4F,315/80R225 B54M F400EZ,0,0.0,572.0,-572.0,REP,30.649,0.000,TR3,22ACT,TBR→225,NaN,NaN,FS400,Firestone,315/80,TBR,TBR(G),TBR(G),NaN
495,202205,外胎,DS,販社,高雄,TBR,進口,TBR0J53F,315/80R22.5 154M D600BZ,10,115050.0,27516.0,87534.0,REP,35.726,357.260,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,315/80,TBR,TBR(G),TBR(G),NaN
524,202205,外胎,FMC,販社,高雄,TBR,進口,TBR0J53F,315/80R22.5 154M D600BZ,15,172575.0,41274.0,131301.0,REP,35.726,535.890,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,315/80,TBR,TBR(G),TBR(G),NaN
639,202205,外胎,A,販社,鶯歌,TBR,進口,TBR0JA4F,315/80R225 B54M F400EZ,0,0.0,286.0,-286.0,REP,30.649,0.000,TR3,22ACT,TBR→225,NaN,NaN,FS400,Firestone,315/80,TBR,TBR(G),TBR(G),NaN
652,202205,外胎,BSSC-FLT,販社,鶯歌,TBR,進口,TBR0J77F,12R22.5 16 152L D600Z,2,23410.0,0.0,23410.0,REP,32.194,64.388,TR3,22ACT,TBR→225,NaN,NaN,D600,MIX,12,TBR,TBR(G),TBR(G),NaN

In [312]:
comparison = comparison.drop(index=[9, 182, 252, 295, 409, 453, 460, 465, 466, 495, 524, 639, 652])

In [313]:
act = act[act["GROUP別"] == "TBR"]

In [314]:
comparison = comparison[comparison["GROUP別"] == "TBR"]

In [315]:
result_act = act.groupby(["GROUP別", "通路-客戶", "預算/前實績"]).apply(lambda x: "{:.0f}".format(x["NET金額"].sum() / x["條數"].sum())).unstack("預算/前實績")
result_act

預算/前實績          22ACT    RT2
GROUP別 通路-客戶
TBR    AG       11738   9866
       FLT-REP   9264   9592
       販社       10855  10889

In [316]:
act.groupby(["GROUP別", "預算/前實績"]).apply(lambda x: "{:.0f}".format(x["NET金額"].sum() / x["條數"].sum())).unstack("預算/前實績")

預算/前實績  22ACT    RT2
GROUP別
TBR     10662  10780

In [317]:
result_comparison = comparison.groupby(["GROUP別", "通路-客戶", "預算/前實績"]).apply(lambda x: "{:.0f}".format(x["NET金額"].sum() / x["條數"].sum())).unstack("預算/前實績")
result_comparison

預算/前實績          22ACT    RT2
GROUP別 通路-客戶
TBR    AG       11738   9866
       FLT-REP   9264   9069
       販社       10929  10889

In [318]:
comparison.groupby(["GROUP別", "預算/前實績"]).apply(lambda x: "{:.0f}".format(x["NET金額"].sum() / x["條數"].sum())).unstack("預算/前實績")

預算/前實績  22ACT    RT2
GROUP別
TBR     10718  10762

In [319]:
10718 / 10762

0.9959115406058353